
# on: [push]
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v2

    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
      # - name: Build project with Maven
      #   run: mvn clean install
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build -x test

    - name: Depcheck
      uses: dependency-check/Dependency-Check_Action@main
      env:
  # actions/setup-java@v1 changes JAVA_HOME so it needs to be reset to match the depcheck image
        JAVA_HOME: /opt/jdk
      id: Depcheck
      with:
        project: 'owasp-dependency-check-github-actions'
        path: '.'
        format: 'HTML'
        out: 'reports' # this is the default, no need to specify unless you wish to override it
        args: >
          --failOnCVSS 7
          --enableRetired
    - name: Upload Test results
      uses: actions/upload-artifact@master
      with:
         name: Depcheck report
         path: ${{github.workspace}}/reports